name: build

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.canary }}
    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-11, windows-2019 ]
        deno-version: [ v1.x ]
        canary: [ false ]
        include:
          - deno-version: canary
            os: ubuntu-18.04
            canary: true
    env:
      DENO_DIR: depcache

    steps:
      - name: Configure line-endings for Windows builds
        if: matrix.os == 'windows-2019'
        run: |
          git config --system core.autocrlf false
          git config --system core.eol lf

      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1.1.0
        with:
          deno-version: ${{ matrix.deno-version }}

      - run: deno fmt --check
      - run: deno lint

      - name: Cache DENO_DIR
        uses: actions/cache@v2
        with:
          path: ${{ env.DENO_DIR }}
          key: ${{ hashFiles('lock.json') }}

      - run: |
          deno test
          --allow-run=git \
          --allow-read \
          --allow-write \
          --lock=lock.json \
          --coverage=cov

      - if: matrix.os == 'ubuntu-20.04'
        run: deno coverage --lcov cov > cov.lcov

      - if: matrix.os == 'ubuntu-20.04'
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: cov.lcov

