name: build

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-11, windows-2019 ]
        deno-version: [ v1.16.x ]
        experimental: [ false ]
        include:
          - deno-version: canary
            os: ubuntu-18.04
            experimental: true
          
    steps:
      - name: Configure line-endings for Windows builds
        if: matrix.os == 'windows-2019'
        run: |
          git config --system core.autocrlf false
          git config --system core.eol lf
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1.1.0
        with:
          deno-version: ${{ matrix.deno-version }}

      - name: Set Deno cache directory
        if: matrix.os == 'ubuntu-20.04'
        run: DENO_DIR=deno_cache

      - name: Cache DENO_DIR
        if: matrix.os == 'ubuntu-20.04'
        uses: actions/cache@v2
        with:
          path: deno_cache
          key: ${{ runner.os }}-deno

      - run: deno fmt --check
      - run: deno lint
      - run: deno run https://deno.land/std@0.117.0/examples/welcome.ts
      # - run: deno test -A --coverage=cov --unstable --cached-only

      - if: matrix.os == 'ubuntu-20.04'
        run: deno coverage --lcov cov > cov.lcov

      - if: matrix.os == 'ubuntu-20.04'
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: cov.lcov
