name: publish egg

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1.1.0
        with:
          deno-version: 1.13
      - name: Release
        run: |
          deno install -Af --unstable https://x.nest.land/eggs@0.3.10/eggs.ts
          eggs link ${{ secrets.NESTAPIKEY }}
          eggs publish -dD --yes --no-check --version $(git describe --tags $(git rev-list --tags --max-count=1))
